<a href="https://colab.research.google.com/github/ashish401/mini_project/blob/main/Minor_Project_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bing-image-downloader

In [ ]:
!mkdir imagesforest

mkdir: cannot create directory ‘imagesforest’: File exists


In [ ]:
from bing_image_downloader import downloader

In [ ]:
downloader.download("green forest",limit=35,output_dir='imagesforest',adult_filter_off=True)

[%] Downloading Images to /content/imagesforest/green forest


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from http://3.bp.blogspot.com/_2UbsSBz9ckE/SbqJjWFBMQI/AAAAAAAAAOQ/u090xPmRqI0/w1200-h630-p-k-no-nu/green-contrast-forest-wallpapers_11431_1600x1200.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/92/a1/e3/92a1e3efb17e94eb378c9678b5e2833a.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://murals-weblinc.netdna-ssl.com/product_images/spring-forest-morning-28679024/5ec82ee4bd89dd0018f76e5f/zoom.jpg?c=1590177508
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/c7/9e/85/c79e85813d5a6a9cd6bc2356ddab7b8f.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/a1/d5/b8/a1d5b81a22684531652a027869133eae.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/99/d7/90/99d790708246cfaecf80a047b4931980.jp

In [ ]:
downloader.download("desert",limit=35,output_dir='imagesforest',adult_filter_off=True)

[%] Downloading Images to /content/imagesforest/desert


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from https://jackfulton.net/wp-content/uploads/2017/02/The-True-Desert.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.familiesworldwide.co.uk/images/galleries/africa_morocco_sahara_desert_gallery_red_sand_dune.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://irantours24.com/wp-content/uploads/2017/10/desert2e.jpg
[!] Issue getting: http://irantours24.com/wp-content/uploads/2017/10/desert2e.jpg
[!] Error:: <urlopen error timed out>
[%] Downloading Image #3 from https://cdn.wallpapersafari.com/48/35/8g1qTb.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.israel-travel-secrets.com/wp-content/uploads/2016/11/Negev-Desert-1280x640.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://living-wild.net/wp-content/uploads/2016/02/true-desert-1.jpg
[%] File Downloaded !

[%] Downloading Image #

In [ ]:
downloader.download("green grass",limit=35,output_dir='imagesforest',adult_filter_off=True)

[%] Downloading Images to /content/imagesforest/green grass


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from http://www.andycain.org/uploads/8/3/6/7/83679422/green-grass_orig.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.wintergreengrass.com/wp-content/uploads/2020/07/TruePutt2.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.wintergreengrass.com/wp-content/uploads/2020/07/TruePutt3.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://syntheticgrasswarehouse.com/wp-content/uploads/2018/02/put29-1030x687.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://turfworksok.com/wp-content/uploads/2019/01/Achieve-a-Super-Green-Turf.png
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/64/88/6d/64886d2f44152c69d8ae8eae9b709762.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://truegreennursery.com.au/website-images/Eureka-Kikuyu.jpg
[!] Issue

In [ ]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

In [ ]:
target = []
images = []
flat_data = []

DATADIR = '/content/imagesforest'
CATEGORIES = ['desert','green forest','green grass']
for category in CATEGORIES:
 class_num= CATEGORIES.index(category) 
 path = os.path.join(DATADIR,category) 
 for img in os.listdir(path):
   img_array = imread(os.path.join(path,img)) 
   img_resized = resize(img_array, (150, 150,3))
   flat_data.append(img_resized.flatten())
   images.append(img_resized)
   target.append(class_num)
   
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)


In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(flat_data,target,
                                        test_size=0.3,random_state=109)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C': [1,10,100,1000], 'kernel': [ 'linear']},
              {'C': [1,10,100,1000], 'gamma': [0.001,0.0001], 'kernel': [ 'rbf']},

]

svc=svm.SVC (probability=True)
clf = GridSearchCV (svc, param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([0, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 1, 2, 0, 1, 1,
       2, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1])

In [ ]:
y_test

array([0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       2, 1, 2, 2, 2, 0, 2, 0, 0, 2, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)

0.7352941176470589

In [ ]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  1],
       [ 2,  6,  5],
       [ 0,  1,  9]])

In [ ]:
import pickle

In [ ]:
pickle.dump(clf,open('img_modle.p','wb'))

In [ ]:
modle = pickle.load(open('img_modle.p','rb'))

In [ ]:
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img, (150, 150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print (f' PREDICTED OUTPUT: {y_out}')

KeyboardInterrupt: ignored